### ISSUE TITLE
Bug or feature? Freeze the game if press inverse key

### ISSUE THREAD

**Issue by rodolfobandeira** [johngrib/vim-game-snake#2]
I'm not sure if this is a bug or intentional feature.

Let's say the snake is moving to the right `-->`. If you press `h` (which is the inverse direction) it freezes the game.

**Comment by johngrib** [comment]
(This is a sentence written using Google Translator.)
In fact, it is not a bug. I have decided on the rule that "if a snake turns back, he will commit suicide."
However, when I received your pull request and played the game, I thought that your suggestion was a better decision. The game is more fun. Thank you. 👍
