### ISSUE TITLE
Ne povas manĝi en akvo

### ISSUE THREAD

**Issue by jorgesumle** [johngrib/vim-game-snake#4]
Mi ne povas manĝi la manĝon de serpento sub akvo.

---

I cannot eat the snake food under water.

![captura](https://user-images.githubusercontent.com/14212780/35325861-e246e3bc-00ec-11e8-890c-5c1b66f9468a.PNG)

**Comment by johngrib** [comment]
https://github.com/johngrib/vim-game-snake/commit/d2d9b6ed9559e1def324bc96da8fa22d56533800

Thanks for reporting bugs.
